install:
	mkdir -p bundle autoload
	curl -Sso autoload/pathogen.vim \
		https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
	cd bundle; git clone https://github.com/tpope/vim-surround.git
	cd bundle; git clone https://github.com/scrooloose/syntastic.git
	cd bundle; git clone https://github.com/editorconfig/editorconfig-vim.git
