install:
	mkdir -p bundle autoload
	curl -Sso autoload/pathogen.vim \
		https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
	cd bundle; git clone git@github.com:tpope/vim-surround.git
